### ISSUE TITLE
access_job_center

### ISSUE THREAD

**Issue by Blomqen** [ESX-Org/esx_joblisting#17]
Accessing job center UI on the blip doesn't seem to work, worked before when it was all in french on the database, i re-uploaded all the sql files in swedish this time and now it doesn't work.

**Comment by Blomqen** [comment]
https://github.com/StockholmCityRP/esx_joblisting used this one instead, seems to work fine

(this one is in swedish by default so you might need to configurate it.)

**Comment by sziler** [comment]
Thanks bro<3 ,good luck!

**Comment by ElPumpo** [comment]
works just fine, idk how you managed to break it all

**Comment by Blomqen** [comment]
> works just fine, idk how you managed to break it all

Worked fine after you fixed it, this comment is from 17 days ago, you [fixed the problem later that day](https://github.com/ESX-Org/esx_joblisting/commit/a3f312e50525f4a7fe2c8a80a60fe0fbce36d2ab), don't know how you could forget that.

**Comment by ElPumpo** [comment]
I could still open the job menu with the previous commit. The problem solved was that the menu could open after you leave the circle.
